### ISSUE TITLE
Issue with upgrading ktlint from v1.4.1 to v1.5.0 or v1.6.0

### ISSUE THREAD

**Issue by ashutosh7107** [cqfn/diKTat#1956]
I am having ktlint v1.4.1 in my project with kotlin v2.0.21 and diktat v2.0.0 and it was working fine but now I wanted to upgrade my ktlint v1.5.0 or 1v.6.0 with diktat v2.0.0 and kotlin v2.0.21 and it is failing with below error. Any idea? How to resolve this error or will that not work due to compatibility issue?

```
:detekt-rules:main: Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.9.21.
Required by:
    project :detekt-rules > com.saveourtool.diktat:diktat-rules:2.0.0
    project :detekt-rules > com.saveourtool.diktat:diktat-rules:2.0.0 > com.saveourtool.diktat:diktat-api:2.0.0
 
Possible solution:
- Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ```

**Comment by ashutosh7107** [comment]
This is almost certainly a compatibility issue, likely due to breaking changes in the KtLint API between v1.4.1 and v1.5.0/v1.6.0.

Custom rule sets like Diktat heavily rely on the internal APIs of KtLint. When KtLint updates its underlying structure (like its Abstract Syntax Tree or internal visitor logic), custom rule sets that haven't been updated to match will fail.

The fact that it works fine with ktlint v1.4.1 but fails when you upgrade to v1.5.0 or v1.6.0 points directly to a change in KtLint that Diktat v2.0.0 doesn't support.

### How to Resolve the Error
You have two main options to fix this:

#### Upgrade Diktat (Recommended)-(Which I don't want to)
The most robust solution is to check for a newer version of Diktat that officially supports KtLint v1.5.0 or v1.6.0.

Go to the official Diktat documentation or GitHub repository and look for a compatibility matrix or release notes.

The Diktat maintainers will have likely released a new version (e.g., v2.1.0 or higher) that has adapted its rules to the new KtLint API.

Action: Update your Diktat dependency to the latest compatible version.

#### Downgrade KtLint (Temporary Workaround) - (Sticking to v1.4.1)
If you are blocked and need an immediate fix, you can revert KtLint to the last known working version:

Action: Stick with ktlint v1.4.1.

Why This Happened
KtLint often makes breaking changes in minor releases (like 1.x.x to 1.y.x) to improve its performance and internal structure. Specifically:

KtLint v1.5.0 and later versions introduced significant internal changes to its Rule Engine and the way custom rules interact with the parsed Kotlin code (AST).

Your Diktat v2.0.0 rules, which were built for the KtLint v1.4.x API, are now calling non-existent or modified methods in the new KtLint v1.5.0/v1.6.0 core, which is what causes the error (e.g., NoClassDefFoundError or similar API-related exceptions).
